name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for creating GitHub Releases.

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: namehash # Comma-separated list of binary names to build and upload.
          tar: none # On which platform to distribute the `.tar.gz` file.
          zip: none # On which platform to distribute the `.zip` file.
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for uploading assets to GitHub Releases.
